# Test steps
test-steps: &test-steps
  steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: npm -v && node -v
    - run: npm install
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    # Run tests
    - run: npm test
    - run:
      name: Upload Coverage
      command: bash <(curl -s https://codecov.io/bash)

version: 2
jobs:
  build-node8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    <<: *test-steps

  build-node10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    <<: *test-steps

workflows:
  version: 2
  build:
    jobs:
      - build-node8
      - build-node10
